name: offline_music
description: A premium offline music player.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  # Packages phục vụ cập nhật UI & Chức năng mới
  image_picker: ^1.0.4
  image_cropper: ^5.0.0
  google_sign_in: ^6.1.5
  googleapis: ^11.4.0
  aad_oauth: ^3.0.1
  http: ^1.1.0
  flutter_downloader: ^1.11.1
  path_provider: ^2.1.1
  # Thêm các package cũ của project vào đây...

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
